### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [SorozhkinNikita/zadanie2#1]
1. https://github.com/SorozhkinNikita/zadanie2/blob/5d0c13ea9f5c02f864a98b9dfbd4b2ded971c4fd/src/main/kotlin/ru/spbstu/nikita/zadanie2/Hello.kt#L7-L9 Лучше записать константы явно через умножение нескольких 1024.
1. Лучше наименования единиц сократить до принятых обозначений (ГБ, МБ, КБ, Б).
1. https://github.com/SorozhkinNikita/zadanie2/blob/5d0c13ea9f5c02f864a98b9dfbd4b2ded971c4fd/src/main/kotlin/ru/spbstu/nikita/zadanie2/Hello.kt#L20 Это, на самом деле, не нужно, `ls` не является аргументом.
1. Вы не проверяете, что задан хотя бы один аргумент.
1. Вы игнорируете некорректные аргументы.
1. Для случая с одним файлом Вы забыли обработать ситуацию без флага `-l`.
1. Вынесите в отдельную функцию форматирование имени файла, чтобы не дублировать его для случаев каталога и отдельного файла.
1. Файлы должны быть отсортированы по имени.
1. Имя выходного файла - это значение опции `-o`, то есть оно не просто второй аргумент с конца, а следующий за `-o`. При этом опции могут идти в любом порядке, то есть может быть так: `-o output.txt -l -h test_dir`.
1. Тесты.

**Comment by SorozhkinNikita** [comment]
Здравствуйте, исправил ошибки, прошу проверить

Если написание тестов обязательно для зачета по этому заданию, мне потребуется ваша помощь
К сожалению у меня не выходит переделать тесты из прошлых заданий
А с нуля не хватает знаний и практики

С уважением, студент группы 3530901/90001, Сорожкин Никита

**Comment by maximpetrov** [comment]
1. Для читаемости лучше было бы не перемножать 1024, а оставить в виде произведения.
1. https://github.com/SorozhkinNikita/zadanie2/blob/450c802023d723e763407a0c4d3f97856a5fe627/src/main/kotlin/ru/spbstu/nikita/zadanie2/Hello.kt#L56 Здесь Вы игнорируете первый (нулевой) аргумент.
1. Непонятно почему переменная называется у Вас `outputDirectory`, хотя это имя файла.
1. https://github.com/SorozhkinNikita/zadanie2/blob/450c802023d723e763407a0c4d3f97856a5fe627/src/main/kotlin/ru/spbstu/nikita/zadanie2/Hello.kt#L65 Непонятная проверка.
1. Собственно, ситуация с проверкой лишних аргументов лучше не стала.
1. Метод `sorted` не сортирует список, а возвращает отсортированный.
1. Возможно, я не совсем корректно сформулировал, но я хотел, чтобы Вы вынесли в отдельную функцию формирование строки для файла, то есть проверку флагов `-l` и `-h` и вызов соответствующего метода.
1. Тесты нужны обязательно. В идеале, нужно проверить работу целиком, но можно проверить хотя бы формирование списка выходных строк. Для этого нужно вынести это формирование в отдельную функцию.
1. Кстати, в writer лучше с использованием `use` работать.

**Comment by SorozhkinNikita** [comment]
Исправил. Тесты буду писать завтра

С уважением, студент группы 3530901/90001, Сорожкин Никита.

**Comment by maximpetrov** [comment]
1. https://github.com/SorozhkinNikita/zadanie2/blob/d38f4f6d2cd2c334b2bd6b7ec7ec50a8d01a9ebb/src/main/kotlin/ru/spbstu/nikita/zadanie2/task2.kt#L73 Неправильно проверять выходной файл на существование. Он может существовать, но в большинстве случаев выходные файлы создаются самой утилитой/программой.
1. https://github.com/SorozhkinNikita/zadanie2/blob/d38f4f6d2cd2c334b2bd6b7ec7ec50a8d01a9ebb/src/main/kotlin/ru/spbstu/nikita/zadanie2/task2.kt#L76 Это не самый лучший способ проверки на лишние аргументы. Лучше просто при нахождении `-o` "проскочить" следующий элемент, тогда любой `else` будет ошибкой. И ещё раз повторюсь, что никакого "ls" не должно быть в списке аргументов.
1. https://github.com/SorozhkinNikita/zadanie2/blob/d38f4f6d2cd2c334b2bd6b7ec7ec50a8d01a9ebb/src/main/kotlin/ru/spbstu/nikita/zadanie2/task2.kt#L81 Почему при `-r` не сортируете?

**Comment by SorozhkinNikita** [comment]
Запушил проект. Список изменений находится в описании коммита.

С уважением, студент группы 3530901/90001, Сорожкин Никита

**Comment by maximpetrov** [comment]
1. В тестах не следует использовать абсолютные пути к файлам, используйте относительные (относительно корня проекта).
1. Пока нет тестов для утилиты целиком или хотя бы для формирования списка строк на основании переданных аргументов.

**Comment by SorozhkinNikita** [comment]
Здравствуйте, исправил


С уважением,
студент группы 3530901/90001,
Сорожкин Никита
